### ISSUE TITLE
Translate cookbook

### ISSUE THREAD

**Issue by ryoichi-obara** [node-red-jp/node-red-jp.github.io#75]
https://nodered.jp/docs/ refers https://cookbook.nodered.org/
Will you translate cookbook and host cookbook.nodered.jp?

**Comment by ryoichi-obara** [comment]
I found https://github.com/node-red-jp/cookbook.nodered.jp , thanks!

**Comment by zuhito** [comment]
Yes, we created the repository! Thank you for your contribution. :)
